apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - fleet-apm-integration.yaml
  - kibana-ingress.yaml
namespace: apm
patches:
  - path: pvc_patch_es.yaml
    target:
      kind: Elasticsearch
      name: elasticsearch