---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-pv-claim
spec:
  storageClassName: fast.ru-7a
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
