---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pl-nats
spec:
  volumeClaimTemplates:
    - metadata:
        name: nats-sts-vol
      spec:
        storageClassName: fast.ru-7a
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
